// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TDFSantaLucia.Data;

#nullable disable

namespace TDFSantaLucia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260713050925_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TDFSantaLucia.Models.ArticuloSalud", b =>
                {
                    b.Property<int>("Articulo_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha_Actualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Imagen_URL")
                        .HasColumnType("longtext");

                    b.Property<bool>("Publicado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Resumen")
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Usuario_Id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Articulo_Id");

                    b.HasIndex("Usuario_Id");

                    b.ToTable("ArticulosSalud");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.CarritoItemDb", b =>
                {
                    b.Property<int>("CarritoItem_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Cliente_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Agregado")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Imagen_URL")
                        .HasColumnType("longtext");

                    b.Property<string>("Marca")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Producto_Id")
                        .HasColumnType("int");

                    b.Property<bool>("Receta")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CarritoItem_Id");

                    b.HasIndex("Cliente_Id");

                    b.ToTable("CarritoItems");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Categoria", b =>
                {
                    b.Property<int>("Categoria_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Categoria_Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.ChatbotOpcion", b =>
                {
                    b.Property<int>("Opcion_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Fecha_Actualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Icono")
                        .HasColumnType("longtext");

                    b.Property<string>("Intent")
                        .HasColumnType("longtext");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Respuesta")
                        .HasColumnType("longtext");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url_Redireccion")
                        .HasColumnType("longtext");

                    b.HasKey("Opcion_Id");

                    b.ToTable("ChatbotOpciones");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Cita", b =>
                {
                    b.Property<int>("Cita_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cliente_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Empleado_Id")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<string>("Servicio")
                        .HasColumnType("longtext");

                    b.HasKey("Cita_Id");

                    b.HasIndex("Cliente_Id");

                    b.HasIndex("Empleado_Id");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Cliente", b =>
                {
                    b.Property<int>("Cliente_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha_Nacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Puntos_Acumulados")
                        .HasColumnType("int");

                    b.Property<string>("Usuario_ID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Cliente_Id");

                    b.HasIndex("Usuario_ID")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.ClienteCupon", b =>
                {
                    b.Property<int>("Cupon_Cliente_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cliente_Id")
                        .HasColumnType("int");

                    b.Property<int>("Cupon_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Asignacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Uso")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Utilizado")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Cupon_Cliente_Id");

                    b.HasIndex("Cliente_Id");

                    b.HasIndex("Cupon_Id");

                    b.ToTable("ClientesCupones");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.ComentarioSalud", b =>
                {
                    b.Property<int>("Comentario_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Articulo_Id")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Usuario_Id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Comentario_Id");

                    b.HasIndex("Articulo_Id");

                    b.HasIndex("Usuario_Id");

                    b.ToTable("ComentariosSalud");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Cupon", b =>
                {
                    b.Property<int>("Cupon_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Fecha_Expiracion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tipo_Descuento")
                        .HasColumnType("longtext");

                    b.Property<string>("Usuario_Id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Valor_Descuento")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Cupon_Id");

                    b.HasIndex("Usuario_Id");

                    b.ToTable("Cupones");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.DetalleFactura", b =>
                {
                    b.Property<int>("Detalle_Factura_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Factura_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio_Unitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Producto_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Detalle_Factura_Id");

                    b.HasIndex("Factura_Id");

                    b.HasIndex("Producto_Id");

                    b.ToTable("DetallesFactura");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.DetallePedido", b =>
                {
                    b.Property<int>("Detalle_Pedido_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Pedido_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio_Unitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Producto_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Detalle_Pedido_Id");

                    b.HasIndex("Pedido_Id");

                    b.HasIndex("Producto_Id");

                    b.ToTable("DetallesPedido");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Empleado", b =>
                {
                    b.Property<int>("Empleado_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion_Exacta")
                        .HasColumnType("longtext");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Puesto")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("SalarioBruto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SalarioNeto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.Property<string>("Usuario_ID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Empleado_Id");

                    b.HasIndex("Usuario_ID")
                        .IsUnique();

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Expediente", b =>
                {
                    b.Property<int>("Expediente_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cliente_Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<int>("Empleado_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Actualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Expediente_Id");

                    b.HasIndex("Cliente_Id");

                    b.HasIndex("Empleado_Id");

                    b.ToTable("Expedientes");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Factura", b =>
                {
                    b.Property<int>("Factura_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cliente_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha_Emision")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Impuesto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Numero_Factura")
                        .HasColumnType("longtext");

                    b.Property<int>("Pedido_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Factura_Id");

                    b.HasIndex("Cliente_Id");

                    b.HasIndex("Pedido_Id");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.HorarioEmpleado", b =>
                {
                    b.Property<int>("Horario_Empleado_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Empleado_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("Fin_Almuerzo")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("Hora_Ingreso")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("Hora_Salida")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("Inicio_Almuerzo")
                        .HasColumnType("time(6)");

                    b.HasKey("Horario_Empleado_Id");

                    b.HasIndex("Empleado_Id");

                    b.ToTable("HorariosEmpleados");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Inventario", b =>
                {
                    b.Property<int>("Inventario_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantidad_Disponible")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad_Minima")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Fecha_Ingreso")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Fecha_Vencimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Numero_Lote")
                        .HasColumnType("longtext");

                    b.Property<int>("Producto_Id")
                        .HasColumnType("int");

                    b.Property<string>("Proveedor")
                        .HasColumnType("longtext");

                    b.HasKey("Inventario_Id");

                    b.HasIndex("Producto_Id");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.LikeArticulo", b =>
                {
                    b.Property<int>("Like_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Articulo_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Usuario_Id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Like_Id");

                    b.HasIndex("Usuario_Id");

                    b.HasIndex("Articulo_Id", "Usuario_Id")
                        .IsUnique();

                    b.ToTable("LikesArticulos");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.MovimientoInventario", b =>
                {
                    b.Property<int>("Movimiento_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha_Movimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Inventario_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Pedido_Id")
                        .HasColumnType("int");

                    b.Property<int>("Producto_Id")
                        .HasColumnType("int");

                    b.Property<string>("Tipo_Movimiento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Usuario_Id")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Movimiento_Id");

                    b.HasIndex("Inventario_Id");

                    b.HasIndex("Pedido_Id");

                    b.HasIndex("Producto_Id");

                    b.HasIndex("Usuario_Id");

                    b.ToTable("MovimientosInventario");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.MovimientoPuntos", b =>
                {
                    b.Property<int>("Movimiento_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cliente_Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Fecha_Vencimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Pedido_Id")
                        .HasColumnType("int");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Vencido")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Movimiento_Id");

                    b.HasIndex("Cliente_Id");

                    b.HasIndex("Pedido_Id");

                    b.ToTable("MovimientosPuntos");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Pedido", b =>
                {
                    b.Property<int>("Pedido_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cliente_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Cupon_Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Descuento_Puntos")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Direccion_Entrega")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado_Receta")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha_Actualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Metodo_Pago")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero_Orden")
                        .HasColumnType("longtext");

                    b.Property<int>("Puntos_Canjeados")
                        .HasColumnType("int");

                    b.Property<int>("Puntos_Ganados")
                        .HasColumnType("int");

                    b.Property<string>("Receta_URL")
                        .HasColumnType("longtext");

                    b.Property<bool>("Requiere_Receta")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Telefono_Contacto")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo_Entrega")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("Uso_Puntos")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Pedido_Id");

                    b.HasIndex("Cliente_Id");

                    b.HasIndex("Cupon_Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Producto", b =>
                {
                    b.Property<int>("Producto_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Categoria_Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Imagen_URL")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("Receta")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Producto_Id");

                    b.HasIndex("Categoria_Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.RecetaMedica", b =>
                {
                    b.Property<int>("Receta_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<int>("Expediente_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Emision")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Fecha_Vencimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Frecuencia")
                        .HasColumnType("longtext");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<int>("Producto_Id")
                        .HasColumnType("int");

                    b.HasKey("Receta_Id");

                    b.HasIndex("Expediente_Id");

                    b.HasIndex("Producto_Id");

                    b.ToTable("RecetasMedicas");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.RecordatorioTratamiento", b =>
                {
                    b.Property<int>("Recordatorio_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Alerta_Activa")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Confirmacion")
                        .HasColumnType("tinyint(1)");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time(6)");

                    b.Property<int>("Tratamiento_Id")
                        .HasColumnType("int");

                    b.HasKey("Recordatorio_Id");

                    b.HasIndex("Tratamiento_Id");

                    b.ToTable("RecordatoriosTratamiento");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Tratamiento", b =>
                {
                    b.Property<int>("Tratamiento_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Alertas_Activas")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Cliente_Id")
                        .HasColumnType("int");

                    b.Property<string>("Dosis")
                        .HasColumnType("longtext");

                    b.Property<string>("Duracion")
                        .HasColumnType("longtext");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Fecha_Fin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Fecha_Inicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre_Medicamento")
                        .HasColumnType("longtext");

                    b.HasKey("Tratamiento_Id");

                    b.HasIndex("Cliente_Id");

                    b.ToTable("Tratamientos");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Cedula")
                        .HasColumnType("longtext");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Correo")
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion_Exacta")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Primer_Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Segundo_Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TDFSantaLucia.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TDFSantaLucia.Models.ArticuloSalud", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Usuario_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.CarritoItemDb", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.Cliente", "Cliente")
                        .WithMany("CarritoItems")
                        .HasForeignKey("Cliente_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Cita", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.Cliente", "Cliente")
                        .WithMany("Citas")
                        .HasForeignKey("Cliente_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDFSantaLucia.Models.Empleado", "Empleado")
                        .WithMany("Citas")
                        .HasForeignKey("Empleado_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Cliente", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.Usuario", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("TDFSantaLucia.Models.Cliente", "Usuario_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.ClienteCupon", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.Cliente", "Cliente")
                        .WithMany("ClienteCupones")
                        .HasForeignKey("Cliente_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDFSantaLucia.Models.Cupon", "Cupon")
                        .WithMany("ClienteCupones")
                        .HasForeignKey("Cupon_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Cupon");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.ComentarioSalud", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.ArticuloSalud", "Articulo")
                        .WithMany("Comentarios")
                        .HasForeignKey("Articulo_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TDFSantaLucia.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Usuario_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Cupon", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Usuario_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.DetalleFactura", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.Factura", "Factura")
                        .WithMany("DetallesFactura")
                        .HasForeignKey("Factura_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDFSantaLucia.Models.Producto", "Producto")
                        .WithMany("DetallesFactura")
                        .HasForeignKey("Producto_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.DetallePedido", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.Pedido", "Pedido")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("Pedido_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDFSantaLucia.Models.Producto", "Producto")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("Producto_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Empleado", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.Usuario", "Usuario")
                        .WithOne("Empleado")
                        .HasForeignKey("TDFSantaLucia.Models.Empleado", "Usuario_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Expediente", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.Cliente", "Cliente")
                        .WithMany("Expedientes")
                        .HasForeignKey("Cliente_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDFSantaLucia.Models.Empleado", "Empleado")
                        .WithMany("Expedientes")
                        .HasForeignKey("Empleado_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Factura", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.Cliente", "Cliente")
                        .WithMany("Facturas")
                        .HasForeignKey("Cliente_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDFSantaLucia.Models.Pedido", "Pedido")
                        .WithMany("Facturas")
                        .HasForeignKey("Pedido_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.HorarioEmpleado", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.Empleado", "Empleado")
                        .WithMany("Horarios")
                        .HasForeignKey("Empleado_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Inventario", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.Producto", "Producto")
                        .WithMany("Inventarios")
                        .HasForeignKey("Producto_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.LikeArticulo", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.ArticuloSalud", "Articulo")
                        .WithMany("Likes")
                        .HasForeignKey("Articulo_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TDFSantaLucia.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Usuario_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.MovimientoInventario", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.Inventario", "Inventario")
                        .WithMany()
                        .HasForeignKey("Inventario_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TDFSantaLucia.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("Pedido_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TDFSantaLucia.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("Producto_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDFSantaLucia.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Usuario_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Inventario");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.MovimientoPuntos", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.Cliente", "Cliente")
                        .WithMany("MovimientosPuntos")
                        .HasForeignKey("Cliente_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TDFSantaLucia.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("Pedido_Id");

                    b.Navigation("Cliente");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Pedido", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("Cliente_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDFSantaLucia.Models.Cupon", "Cupon")
                        .WithMany("Pedidos")
                        .HasForeignKey("Cupon_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Cupon");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Producto", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("Categoria_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.RecetaMedica", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.Expediente", "Expediente")
                        .WithMany("RecetasMedicas")
                        .HasForeignKey("Expediente_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TDFSantaLucia.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("Producto_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expediente");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.RecordatorioTratamiento", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.Tratamiento", "Tratamiento")
                        .WithMany("Recordatorios")
                        .HasForeignKey("Tratamiento_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Tratamiento", b =>
                {
                    b.HasOne("TDFSantaLucia.Models.Cliente", "Cliente")
                        .WithMany("Tratamientos")
                        .HasForeignKey("Cliente_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.ArticuloSalud", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Cliente", b =>
                {
                    b.Navigation("CarritoItems");

                    b.Navigation("Citas");

                    b.Navigation("ClienteCupones");

                    b.Navigation("Expedientes");

                    b.Navigation("Facturas");

                    b.Navigation("MovimientosPuntos");

                    b.Navigation("Pedidos");

                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Cupon", b =>
                {
                    b.Navigation("ClienteCupones");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Empleado", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Expedientes");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Expediente", b =>
                {
                    b.Navigation("RecetasMedicas");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Factura", b =>
                {
                    b.Navigation("DetallesFactura");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Pedido", b =>
                {
                    b.Navigation("DetallesPedido");

                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Producto", b =>
                {
                    b.Navigation("DetallesFactura");

                    b.Navigation("DetallesPedido");

                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Tratamiento", b =>
                {
                    b.Navigation("Recordatorios");
                });

            modelBuilder.Entity("TDFSantaLucia.Models.Usuario", b =>
                {
                    b.Navigation("Cliente");

                    b.Navigation("Empleado");
                });
#pragma warning restore 612, 618
        }
    }
}
